### ISSUE TITLE
One shot command and feedback for high rate control

### ISSUE THREAD

**Issue by ThotAlion** [tinymovr/Tinymovr#142]
For high rate motor control at server level, it should be interesting to have a function in API which sends goal position by CAN and recup the feedbacks (position, speed, temperature, etc).
In "one shot" of CAN, you can give an order and get feedback.

Kind of :

...
[pos,speed,iq,temp] = tm.send_get_position(position,speed_feed_forward,current_feed_forward)
...

**Comment by yconst** [comment]
Sounds good. The cleanest way this could be implemented is to 'overload' the read endpoints to accept setting values, by clearing the RTR bit. Then, the 'request' frame would also set the values, and Tinymovr would respond with a response frame as usual.
This could be implemented for a handful of real-time endpoints.
The data returned would be the same as the ones supported by the endpoint.

**Comment by yconst** [comment]
Fixed by #155
