### ISSUE TITLE
CAN Watchdog option

### ISSUE THREAD

**Issue by amcunio** [tinymovr/Tinymovr#191]
We are wanting some additional functionality for the firmware to have a watchdog that halts the motor if it stops receiving CAN messages on the bus.

If we were to implement this, would this be likely to be merged in. Additionally, are there any design requirements that you have for the overall repository that would help this in getting passed through.

**Comment by yconst** [comment]
Thank you for the comment. Yes, we would like to merge as this is a desired functionality.

We run a firmware build and cppcheck for each board revision during CI. In C we loosely follow the [Google Style guide](https://github.com/google/styleguide). And in Python we try to use [Black](https://github.com/psf/black).

That's all. Just open a pull request when you are ready.

Thanks.
