### ISSUE TITLE
ModuleNotFoundError: No module named 'PySide2'

### ISSUE THREAD

**Issue by ator1811** [tinymovr/Tinymovr#253]
I installed the Tinumover Studio according to [https://tinymovr.readthedocs.io/en/latest/studio/installation.html](url) using Conda.
`conda create --name tinymovr python=3.10 -y`
`conda activate tinymovr` 

After `pip install tinymovr` and starting tinymovr a message appears stating `ModuleNotFoundError: No module named 'PySide2'`. What is wrong?

**Comment by yconst** [comment]
Please note the the guide and Studio release have just been updated to address this issue. So doing:

    pip install 'tinymovr[GUI]'
    tinymovr

Should install Studio 1.2.8 and should work. The only platform we're seeing issues is Apple ARM. If you are in this platform, we'll publish a new fix soon.

**Comment by ator1811** [comment]
Thx, I'm on an Apple ARM. I followed the Anaconda procedure and not the PIP procedure.

**Comment by yconst** [comment]
Note that you should still be able to use the CLI:

    tinymovr_cli

**Comment by ator1811** [comment]
Thx, in the documentation under Anaconda installation [https://tinymovr.readthedocs.io/en/latest/studio/installation.html#anaconda-installation](url), the pip install command must be changed as well
